Repository fsiwi-hka/iwi-website, pull requests merged in 2021-11, with the labels that each got.

#92 feat: Add LICENSE
  LICENSE
Labels: documentation

#91 fixed flexbox bug for cooperation logos
  content/pages/unternehmen.md
Labels: bug

#79 Implement and style user account menu
  components/common/menu.tsx
  styles/index.css
Labels: blocked
